include ../Makefile.inc

CFLAGS	= $(CFLAGS_INC)
OBJLIBS	= libcgimg.a
SRCS     = $(wildcard *.cpp)
OBJS 	 = $(SRCS:.cpp=.o)

all : $(OBJLIBS)

%.o: %.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJLIBS) : $(OBJS)
	$(AR) $(ARFLAGS) rv ../$(OBJLIBS) $?
	$(RANLIB) ../$(OBJLIBS)

clean :
	$(ECHO) cleaning up in subdir
	-$(RM) -f $(OBJS) *~

force_look :
	true

